# Generated by Django 3.1.5 on 2021-01-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210109_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=2)),
                ('spot', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
